### ISSUE TITLE
Module doesn't work properly at all

### ISSUE THREAD

**Issue by TheJoshue** [samerton/Nameless-Resources#14]
Resources Module version I am using here is latest (1.1.1)

This is what happens in StaffCP (panel)
http://prntscr.com/t0vjm3

If you press "Downloads" it does error 404

**Comment by samerton** [comment]
The problem with the navbar is that both the resources module and the vote module have the same navbar order value, one of the modules will need its navbar order value changing, unfortunately there is no fix you can apply yourself until one of the modules updates.

As for the downloads page returning a 404, this is because the page hasn't been implemented yet and is coming soon.

**Comment by TheJoshue** [comment]
How can we post resources then?

**Comment by samerton** [comment]
Resources are posted through the front end, in the normal resources page when you click through to a category.
